if(NOT DEFINED CLI)
    message(FATAL_ERROR "CLI is required")
endif()
if(NOT DEFINED VAT_WRITER)
    message(FATAL_ERROR "VAT_WRITER is required")
endif()
if(NOT DEFINED OUT_DIR)
    message(FATAL_ERROR "OUT_DIR is required")
endif()

file(REMOVE_RECURSE "${OUT_DIR}")
file(MAKE_DIRECTORY "${OUT_DIR}")

function(expect_contains text needle label)
    string(FIND "${text}" "${needle}" found_at)
    if(found_at EQUAL -1)
        message(FATAL_ERROR "${label} did not contain expected text:\n${needle}\n\nActual:\n${text}")
    endif()
endfunction()

function(make_project out_var name asset_json ui_json)
    set(root "${OUT_DIR}/${name}")
    file(MAKE_DIRECTORY "${root}/assets" "${root}/ui")
    file(WRITE "${root}/project.json" [=[
{
  "schema": "pelican.project",
  "version": 1,
  "name": "dist-config fixture",
  "engine_min_version": "0.1.0",
  "basic_config": {
    "asset_data_json": "assets/asset_data.json",
    "ui_config_json": "ui/ui.json"
  }
}
]=])
    file(WRITE "${root}/assets/asset_data.json" "${asset_json}\n")
    file(WRITE "${root}/ui/ui.json" "${ui_json}\n")
    set(${out_var} "${root}" PARENT_SCOPE)
endfunction()

function(run_dist_config name project_dir expected_vat expected_exr expected_rpc expected_seq expected_openxr)
    set(preset "${OUT_DIR}/${name}.cmake")
    set(command "${CLI}" dist-config "${project_dir}" --out "${preset}")
    if(ARGC GREATER 7)
        list(APPEND command --with "${ARGV7}")
    endif()

    execute_process(
        COMMAND ${command}
        RESULT_VARIABLE result
        OUTPUT_VARIABLE stdout
        ERROR_VARIABLE stderr
    )
    if(NOT result EQUAL 0)
        message(FATAL_ERROR "dist-config ${name} failed with ${result}\nstdout:\n${stdout}\nstderr:\n${stderr}")
    endif()

    file(READ "${preset}" contents)
    expect_contains("${contents}" "# Generated by pelican_cli dist-config" "${name} header")
    expect_contains("${contents}" "# Project:" "${name} project comment")
    expect_contains("${contents}" "# Generated at:" "${name} timestamp comment")
    expect_contains("${contents}" "# PELICAN_WITH_VAT: ${expected_vat} -" "${name} VAT comment")
    expect_contains("${contents}" "# PELICAN_WITH_EXR: ${expected_exr} -" "${name} EXR comment")
    expect_contains("${contents}" "# PELICAN_WITH_RPC: ${expected_rpc} -" "${name} RPC comment")
    expect_contains("${contents}" "# PELICAN_WITH_SEQPLAYER: ${expected_seq} -" "${name} SeqPlayer comment")
    expect_contains("${contents}" "# PELICAN_WITH_OPENXR: ${expected_openxr} -" "${name} OpenXR comment")
    expect_contains("${contents}" "set(PELICAN_WITH_VAT ${expected_vat} CACHE BOOL \"\" FORCE)" "${name} VAT flag")
    expect_contains("${contents}" "set(PELICAN_WITH_EXR ${expected_exr} CACHE BOOL \"\" FORCE)" "${name} EXR flag")
    expect_contains("${contents}" "set(PELICAN_WITH_RPC ${expected_rpc} CACHE BOOL \"\" FORCE)" "${name} RPC flag")
    expect_contains("${contents}" "set(PELICAN_WITH_SEQPLAYER ${expected_seq} CACHE BOOL \"\" FORCE)" "${name} SeqPlayer flag")
    expect_contains("${contents}" "set(PELICAN_WITH_OPENXR ${expected_openxr} CACHE BOOL \"\" FORCE)" "${name} OpenXR flag")
    expect_contains("${contents}" "set(PELICAN_WITH_IMGUI OFF CACHE BOOL \"\" FORCE)" "${name} ImGui flag")
    expect_contains("${contents}" "set(PELICAN_WITH_RENDERDOC OFF CACHE BOOL \"\" FORCE)" "${name} RenderDoc flag")
    expect_contains("${contents}" "set(PELICAN_WITH_SPIRV_LINK OFF CACHE BOOL \"\" FORCE)" "${name} SPIR-V linker flag")
    expect_contains("${contents}" "set(BUILD_TESTING OFF CACHE BOOL \"\" FORCE)" "${name} test tooling flag")

    if(expected_vat STREQUAL "ON")
        expect_contains("${contents}" "pelican.vat extras" "${name} VAT evidence")
    endif()
    if(expected_exr STREQUAL "ON")
        expect_contains("${contents}" ".EXR" "${name} EXR evidence")
    endif()
    if(expected_rpc STREQUAL "ON")
        expect_contains("${contents}" "enabled by --with rpc" "${name} RPC evidence")
    endif()
    if(expected_seq STREQUAL "ON")
        expect_contains("${contents}" "enabled by --with seqplayer" "${name} SeqPlayer evidence")
    endif()
    if(expected_openxr STREQUAL "ON")
        expect_contains("${contents}" "enabled by --with openxr" "${name} OpenXR evidence")
    endif()
endfunction()

make_project(PLAIN_ROOT plain [=[
{
  "models": []
}
]=] [=[
{"schema":"pelican.ui","version":1,"key":"empty","root":{"id":"root","type":"panel"}}
]=])

make_project(VAT_ROOT vat_asset [=[
{
  "models": [
    {"name": "vat", "path": "assets/tiny_vat.glb"}
  ]
}
]=] [=[
{"schema":"pelican.ui","version":1,"key":"empty","root":{"id":"root","type":"panel"}}
]=])
execute_process(
    COMMAND "${VAT_WRITER}" "${VAT_ROOT}/assets/tiny_vat.glb"
    RESULT_VARIABLE vat_writer_result
    OUTPUT_VARIABLE vat_writer_stdout
    ERROR_VARIABLE vat_writer_stderr
)
if(NOT vat_writer_result EQUAL 0)
    message(FATAL_ERROR "VAT fixture writer failed\nstdout:\n${vat_writer_stdout}\nstderr:\n${vat_writer_stderr}")
endif()

make_project(EXR_ROOT exr_ui [=[
{"models":[]}
]=] [=[
{
  "images": [
    {"name": "beauty", "file": "assets/textures/beauty.EXR"}
  ]
}
]=])

make_project(MANIFEST_ROOT vat_manifest [=[
{"models":[]}
]=] [=[
{"schema":"pelican.ui","version":1,"key":"empty","root":{"id":"root","type":"panel"}}
]=])
file(MAKE_DIRECTORY "${MANIFEST_ROOT}/imports/houdini/delivery")
execute_process(
    COMMAND "${VAT_WRITER}" "${MANIFEST_ROOT}/imports/houdini/delivery/tiny_vat.glb"
    RESULT_VARIABLE manifest_writer_result
    OUTPUT_VARIABLE manifest_writer_stdout
    ERROR_VARIABLE manifest_writer_stderr
)
if(NOT manifest_writer_result EQUAL 0)
    message(FATAL_ERROR "manifest VAT fixture writer failed\nstdout:\n${manifest_writer_stdout}\nstderr:\n${manifest_writer_stderr}")
endif()
file(WRITE "${MANIFEST_ROOT}/imports/houdini/delivery/manifest.json" [=[
{
  "schema": "pelican.import",
  "version": 1,
  "tool": {"name": "fixture"},
  "source": {"file": "fixture.hip"},
  "created": "2026-07-07T00:00:00Z",
  "outputs": [
    {
      "file": "tiny_vat.glb",
      "schema": "gltf",
      "sha256": "0000000000000000000000000000000000000000000000000000000000000000"
    }
  ]
}
]=])

run_dist_config("plain" "${PLAIN_ROOT}" OFF OFF OFF OFF OFF)
run_dist_config("vat_asset" "${VAT_ROOT}" ON OFF OFF OFF OFF)
run_dist_config("exr_ui" "${EXR_ROOT}" OFF ON OFF OFF OFF)
run_dist_config("vat_manifest" "${MANIFEST_ROOT}" ON OFF OFF OFF OFF)
run_dist_config("with_overrides" "${PLAIN_ROOT}" OFF OFF ON ON ON "rpc,seqplayer,openxr")
