#ifndef PELICAN_SETS_GLSL
#define PELICAN_SETS_GLSL

#define PELICAN_SET_FRAME 0
#define PELICAN_SET_PASS_INPUT 1
#define PELICAN_SET_MATERIAL 2
#define PELICAN_SET_FREE 3

#define PELICAN_PUSH_ENGINE_BYTES 64
#define PELICAN_PUSH_SHADER_BYTES 64
#define PELICAN_PUSH_TOTAL_BYTES 128

#endif
