#ifndef PELICAN_LIGHTING_V2_GLSL
#define PELICAN_LIGHTING_V2_GLSL

// Public scalable-light inventory and fixed-stride tiled selection contract.
// Descriptor declarations and bindings are generated by
// pelican_resource_ports.glsl; this library owns only the packed data ABI.
const uint PELICAN_LIGHT_INVENTORY_V2_MAGIC = 0x504C4932u;
const uint PELICAN_LIGHT_INVENTORY_V2_VERSION = 2u;
const uint PELICAN_LIGHT_SELECTION_V1_MAGIC = 0x504C5331u;
const uint PELICAN_LIGHT_SELECTION_V1_VERSION = 1u;
const uint PELICAN_LIGHT_SELECTION_OVERFLOW_BIT = 0x80000000u;
const uint PELICAN_LIGHT_SELECTION_COUNT_MASK = 0x7fffffffu;

bool pelican_light_inventory_v2_valid() {
    if (pelican_count_light_inventory() < 2u) {
        return false;
    }
    uvec4 header = pelican_load_light_inventory(0u);
    uint required = 2u + header.z * 4u;
    return header.x == PELICAN_LIGHT_INVENTORY_V2_MAGIC &&
           header.y == PELICAN_LIGHT_INVENTORY_V2_VERSION &&
           required >= 2u &&
           required <= pelican_count_light_inventory();
}

uvec4 pelican_light_selection_header_a() {
    return uvec4(
        pelican_load_light_selection(0u),
        pelican_load_light_selection(1u),
        pelican_load_light_selection(2u),
        pelican_load_light_selection(3u));
}

uvec4 pelican_light_selection_header_b() {
    return uvec4(
        pelican_load_light_selection(4u),
        pelican_load_light_selection(5u),
        pelican_load_light_selection(6u),
        pelican_load_light_selection(7u));
}

bool pelican_light_selection_v1_valid() {
    if (!pelican_light_inventory_v2_valid() ||
        pelican_count_light_selection() < 8u) {
        return false;
    }
    uvec4 a = pelican_light_selection_header_a();
    uvec4 b = pelican_light_selection_header_b();
    if (a.x != PELICAN_LIGHT_SELECTION_V1_MAGIC ||
        a.y != PELICAN_LIGHT_SELECTION_V1_VERSION ||
        a.z == 0u || a.w == 0u ||
        b.x == 0u || b.y == 0u || b.z == 0u) {
        return false;
    }
    uint tile_count = a.z * a.w;
    uint stride = 1u + b.z;
    uint required = 8u + tile_count * stride;
    return tile_count != 0u && stride > b.z &&
           required >= 8u &&
           required <= pelican_count_light_selection();
}

uint pelican_light_selection_tile_base() {
    uvec4 a = pelican_light_selection_header_a();
    uvec4 b = pelican_light_selection_header_b();
    uint tile_x = min(
        uint(max(gl_FragCoord.x, 0.0)) / b.x,
        a.z - 1u);
    uint tile_y = min(
        uint(max(gl_FragCoord.y, 0.0)) / b.y,
        a.w - 1u);
    return 8u +
           (tile_y * a.z + tile_x) *
               (1u + b.z);
}

uint pelican_legacy_light_count_v2() {
    return pelicanLights.directionalLightCount +
           pelicanLights.pointLightCount +
           pelicanLights.spotLightCount;
}

uint pelican_directional_light_count() {
    if (!pelican_light_selection_v1_valid()) {
        return pelicanLights.directionalLightCount;
    }
    return pelican_load_light_inventory(1u).x;
}

uint pelican_light_count() {
    if (!pelican_light_selection_v1_valid()) {
        return pelican_legacy_light_count_v2();
    }
    uint encoded = pelican_load_light_selection(
        pelican_light_selection_tile_base());
    return encoded &
           PELICAN_LIGHT_SELECTION_COUNT_MASK;
}

bool pelican_light_selection_overflowed() {
    if (!pelican_light_selection_v1_valid()) {
        return false;
    }
    uint encoded = pelican_load_light_selection(
        pelican_light_selection_tile_base());
    return (encoded &
            PELICAN_LIGHT_SELECTION_OVERFLOW_BIT) != 0u;
}

uint pelican_light_inventory_index(uint local_index) {
    if (!pelican_light_selection_v1_valid()) {
        return local_index;
    }
    uint base = pelican_light_selection_tile_base();
    return pelican_load_light_selection(
        base + 1u + local_index);
}

PelicanLightV1 pelican_legacy_light_v2(
    uint index, vec3 world_position) {
    PelicanLightV1 light;
    light.direction = vec3(0.0, 1.0, 0.0);
    light.radiance = vec3(0.0);
    light.attenuation = 1.0;
    if (index < pelicanLights.directionalLightCount) {
        PelicanDirectionalLight source =
            pelicanLights.directionalLights[index];
        light.direction = normalize(-source.direction);
        light.radiance =
            source.color * source.intensity;
        return light;
    }
    index -= pelicanLights.directionalLightCount;
    if (index < pelicanLights.pointLightCount) {
        PelicanPointLight source =
            pelicanLights.pointLights[index];
        vec3 delta = source.position - world_position;
        float distance_squared =
            max(dot(delta, delta), 0.0001);
        light.direction = normalize(delta);
        light.attenuation = 1.0 / distance_squared;
        light.radiance =
            source.color * source.intensity;
        return light;
    }
    index -= pelicanLights.pointLightCount;
    if (index < pelicanLights.spotLightCount) {
        PelicanSpotLight source =
            pelicanLights.spotLights[index];
        vec3 delta = source.position - world_position;
        float distance_squared =
            max(dot(delta, delta), 0.0001);
        light.direction = normalize(delta);
        float cone = dot(
            normalize(source.direction),
            -light.direction);
        float cone_weight = smoothstep(
            source.outerConeAngle,
            source.innerConeAngle, cone);
        light.attenuation =
            cone_weight / distance_squared;
        light.radiance =
            source.color * source.intensity;
    }
    return light;
}

PelicanLightV1 pelican_light(
    uint local_index, vec3 world_position) {
    if (!pelican_light_selection_v1_valid()) {
        return pelican_legacy_light_v2(
            local_index, world_position);
    }

    uint inventory_index =
        pelican_light_inventory_index(local_index);
    uvec4 inventory_header =
        pelican_load_light_inventory(0u);
    if (inventory_index >= inventory_header.z) {
        PelicanLightV1 empty_light;
        empty_light.direction =
            vec3(0.0, 1.0, 0.0);
        empty_light.radiance = vec3(0.0);
        empty_light.attenuation = 0.0;
        return empty_light;
    }
    uint base = 2u + inventory_index * 4u;
    uvec4 metadata =
        pelican_load_light_inventory(base);
    vec4 payload0 = uintBitsToFloat(
        pelican_load_light_inventory(base + 1u));
    vec4 payload1 = uintBitsToFloat(
        pelican_load_light_inventory(base + 2u));
    vec4 payload2 = uintBitsToFloat(
        pelican_load_light_inventory(base + 3u));

    PelicanLightV1 light;
    light.direction = vec3(0.0, 1.0, 0.0);
    light.radiance =
        payload1.rgb * payload0.w;
    light.attenuation = 1.0;
    if (metadata.x == 0u) {
        light.direction =
            normalize(-payload0.xyz);
        return light;
    }

    vec3 delta =
        payload0.xyz - world_position;
    float distance_squared =
        max(dot(delta, delta), 0.0001);
    light.direction = normalize(delta);
    light.attenuation =
        1.0 / distance_squared;
    if (metadata.x == 2u) {
        float cone = dot(
            normalize(payload2.xyz),
            -light.direction);
        float cone_weight = smoothstep(
            payload1.w, payload2.w, cone);
        light.attenuation *= cone_weight;
    }
    return light;
}

#endif
