#ifndef PELICAN_LIGHTING_V2_GLSL
#define PELICAN_LIGHTING_V2_GLSL

// Public scalable-light inventory and fixed-stride tiled selection contract.
// Descriptor declarations and bindings are generated by
// pelican_resource_ports.glsl; this library owns only the packed data ABI.
const uint PELICAN_LIGHT_INVENTORY_V2_MAGIC = 0x504C4932u;
const uint PELICAN_LIGHT_INVENTORY_V2_VERSION = 2u;
const uint PELICAN_LIGHT_SELECTION_V2_MAGIC = 0x504C5332u;
const uint PELICAN_LIGHT_SELECTION_V2_VERSION = 2u;
const uint PELICAN_LIGHT_SELECTION_OVERFLOW_BIT = 0x80000000u;
const uint PELICAN_LIGHT_SELECTION_COUNT_MASK = 0x7fffffffu;
const uint PELICAN_LIGHT_SELECTION_V2_HEADER_WORDS = 12u;

bool pelican_light_inventory_v2_valid() {
    if (pelican_count_light_inventory() < 2u) {
        return false;
    }
    uvec4 header = pelican_load_light_inventory(0u);
    uint required = 2u + header.z * 4u;
    return header.x == PELICAN_LIGHT_INVENTORY_V2_MAGIC &&
           header.y == PELICAN_LIGHT_INVENTORY_V2_VERSION &&
           required >= 2u &&
           required <= pelican_count_light_inventory();
}

bool pelican_light_selection_region(
    out uint region_base,
    out uint region_words) {
    uint view_index = pelican_view_index();
    uint view_count = pelican_view_count();
    uint total_words =
        pelican_count_light_selection();
    if (view_count == 0u ||
        view_index >= view_count ||
        total_words % view_count != 0u) {
        region_base = 0u;
        region_words = 0u;
        return false;
    }
    region_words = total_words / view_count;
    region_base = view_index * region_words;
    return region_words >=
           PELICAN_LIGHT_SELECTION_V2_HEADER_WORDS;
}

uvec4 pelican_light_selection_header_a(
    uint region_base) {
    return uvec4(
        pelican_load_light_selection(region_base + 0u),
        pelican_load_light_selection(region_base + 1u),
        pelican_load_light_selection(region_base + 2u),
        pelican_load_light_selection(region_base + 3u));
}

uvec4 pelican_light_selection_header_b(
    uint region_base) {
    return uvec4(
        pelican_load_light_selection(region_base + 4u),
        pelican_load_light_selection(region_base + 5u),
        pelican_load_light_selection(region_base + 6u),
        pelican_load_light_selection(region_base + 7u));
}

uvec4 pelican_light_selection_header_c(
    uint region_base) {
    return uvec4(
        pelican_load_light_selection(region_base + 8u),
        pelican_load_light_selection(region_base + 9u),
        pelican_load_light_selection(region_base + 10u),
        pelican_load_light_selection(region_base + 11u));
}

bool pelican_light_selection_v2_valid() {
    uint region_base = 0u;
    uint region_words = 0u;
    if (!pelican_light_inventory_v2_valid() ||
        !pelican_light_selection_region(
            region_base, region_words)) {
        return false;
    }
    uvec4 a =
        pelican_light_selection_header_a(region_base);
    uvec4 b =
        pelican_light_selection_header_b(region_base);
    uvec4 c =
        pelican_light_selection_header_c(region_base);
    uvec2 family_token =
        pelican_view_family_token();
    if (a.x != PELICAN_LIGHT_SELECTION_V2_MAGIC ||
        a.y != PELICAN_LIGHT_SELECTION_V2_VERSION ||
        a.z == 0u || a.w == 0u ||
        b.x == 0u || b.y == 0u || b.z == 0u ||
        c.x != pelican_view_index() ||
        c.y != pelican_view_count() ||
        c.z != family_token.x ||
        c.w != family_token.y) {
        return false;
    }
    uint tile_count = a.z * a.w;
    uint stride = 1u + b.z;
    uint required =
        PELICAN_LIGHT_SELECTION_V2_HEADER_WORDS +
        tile_count * stride;
    return tile_count != 0u && stride > b.z &&
           required >=
               PELICAN_LIGHT_SELECTION_V2_HEADER_WORDS &&
           required <= region_words;
}

uint pelican_light_selection_tile_base() {
    uint region_base = 0u;
    uint region_words = 0u;
    pelican_light_selection_region(
        region_base, region_words);
    uvec4 a =
        pelican_light_selection_header_a(region_base);
    uvec4 b =
        pelican_light_selection_header_b(region_base);
    uint tile_x = min(
        uint(max(gl_FragCoord.x, 0.0)) / b.x,
        a.z - 1u);
    uint tile_y = min(
        uint(max(gl_FragCoord.y, 0.0)) / b.y,
        a.w - 1u);
    return region_base +
           PELICAN_LIGHT_SELECTION_V2_HEADER_WORDS +
           (tile_y * a.z + tile_x) *
               (1u + b.z);
}

uint pelican_legacy_light_count_v2() {
    return pelicanLights.directionalLightCount +
           pelicanLights.pointLightCount +
           pelicanLights.spotLightCount;
}

uint pelican_directional_light_count() {
    if (!pelican_light_selection_v2_valid()) {
        return pelicanLights.directionalLightCount;
    }
    return pelican_load_light_inventory(1u).x;
}

uint pelican_light_count() {
    if (!pelican_light_selection_v2_valid()) {
        return pelican_legacy_light_count_v2();
    }
    uint encoded = pelican_load_light_selection(
        pelican_light_selection_tile_base());
    return encoded &
           PELICAN_LIGHT_SELECTION_COUNT_MASK;
}

bool pelican_light_selection_overflowed() {
    if (!pelican_light_selection_v2_valid()) {
        return false;
    }
    uint encoded = pelican_load_light_selection(
        pelican_light_selection_tile_base());
    return (encoded &
            PELICAN_LIGHT_SELECTION_OVERFLOW_BIT) != 0u;
}

uint pelican_light_inventory_index(uint local_index) {
    if (!pelican_light_selection_v2_valid()) {
        return local_index;
    }
    uint base = pelican_light_selection_tile_base();
    return pelican_load_light_selection(
        base + 1u + local_index);
}

PelicanLightV1 pelican_legacy_light_v2(
    uint index, vec3 world_position) {
    PelicanLightV1 light;
    light.direction = vec3(0.0, 1.0, 0.0);
    light.radiance = vec3(0.0);
    light.attenuation = 1.0;
    if (index < pelicanLights.directionalLightCount) {
        PelicanDirectionalLight source =
            pelicanLights.directionalLights[index];
        light.direction = normalize(-source.direction);
        light.radiance =
            source.color * source.intensity;
        return light;
    }
    index -= pelicanLights.directionalLightCount;
    if (index < pelicanLights.pointLightCount) {
        PelicanPointLight source =
            pelicanLights.pointLights[index];
        vec3 delta = source.position - world_position;
        float distance_squared =
            max(dot(delta, delta), 0.0001);
        light.direction = normalize(delta);
        light.attenuation = 1.0 / distance_squared;
        light.radiance =
            source.color * source.intensity;
        return light;
    }
    index -= pelicanLights.pointLightCount;
    if (index < pelicanLights.spotLightCount) {
        PelicanSpotLight source =
            pelicanLights.spotLights[index];
        vec3 delta = source.position - world_position;
        float distance_squared =
            max(dot(delta, delta), 0.0001);
        light.direction = normalize(delta);
        float cone = dot(
            normalize(source.direction),
            -light.direction);
        float cone_weight = smoothstep(
            source.outerConeAngle,
            source.innerConeAngle, cone);
        light.attenuation =
            cone_weight / distance_squared;
        light.radiance =
            source.color * source.intensity;
    }
    return light;
}

PelicanLightV1 pelican_light(
    uint local_index, vec3 world_position) {
    if (!pelican_light_selection_v2_valid()) {
        return pelican_legacy_light_v2(
            local_index, world_position);
    }

    uint inventory_index =
        pelican_light_inventory_index(local_index);
    uvec4 inventory_header =
        pelican_load_light_inventory(0u);
    if (inventory_index >= inventory_header.z) {
        PelicanLightV1 empty_light;
        empty_light.direction =
            vec3(0.0, 1.0, 0.0);
        empty_light.radiance = vec3(0.0);
        empty_light.attenuation = 0.0;
        return empty_light;
    }
    uint base = 2u + inventory_index * 4u;
    uvec4 metadata =
        pelican_load_light_inventory(base);
    vec4 payload0 = uintBitsToFloat(
        pelican_load_light_inventory(base + 1u));
    vec4 payload1 = uintBitsToFloat(
        pelican_load_light_inventory(base + 2u));
    vec4 payload2 = uintBitsToFloat(
        pelican_load_light_inventory(base + 3u));

    PelicanLightV1 light;
    light.direction = vec3(0.0, 1.0, 0.0);
    light.radiance =
        payload1.rgb * payload0.w;
    light.attenuation = 1.0;
    if (metadata.x == 0u) {
        light.direction =
            normalize(-payload0.xyz);
        return light;
    }

    vec3 delta =
        payload0.xyz - world_position;
    float distance_squared =
        max(dot(delta, delta), 0.0001);
    light.direction = normalize(delta);
    light.attenuation =
        1.0 / distance_squared;
    if (metadata.x == 2u) {
        float cone = dot(
            normalize(payload2.xyz),
            -light.direction);
        float cone_weight = smoothstep(
            payload1.w, payload2.w, cone);
        light.attenuation *= cone_weight;
    }
    return light;
}

#endif
