# Pelican's Vulkan API and shader target contract is declared only here.
#
# Vulkan 1.3 remains the engine API target because the renderer uses core
# dynamic rendering.  The shader toolchain deliberately targets Vulkan 1.2 /
# SPIR-V 1.5: it already satisfies the known SPIR-V 1.4+ requirement without
# needlessly raising the runtime-compiler and linker output to SPIR-V 1.6.
set(PELICAN_VULKAN_API_TARGET_VERSION "1.3.283")
set(PELICAN_SHADER_TARGET_ENV "vulkan1.2")

string(REGEX MATCH "^([0-9]+)\\.([0-9]+)\\.([0-9]+)$"
  PELICAN_VULKAN_API_TARGET_MATCH
  "${PELICAN_VULKAN_API_TARGET_VERSION}"
)
if(NOT PELICAN_VULKAN_API_TARGET_MATCH)
  message(FATAL_ERROR
    "Invalid PELICAN_VULKAN_API_TARGET_VERSION: "
    "${PELICAN_VULKAN_API_TARGET_VERSION}")
endif()
set(PELICAN_VULKAN_API_TARGET_MAJOR "${CMAKE_MATCH_1}")
set(PELICAN_VULKAN_API_TARGET_MINOR "${CMAKE_MATCH_2}")
set(PELICAN_VULKAN_API_TARGET_PATCH "${CMAKE_MATCH_3}")

string(REGEX MATCH "^vulkan([0-9]+)\\.([0-9]+)$"
  PELICAN_SHADER_TARGET_ENV_MATCH
  "${PELICAN_SHADER_TARGET_ENV}"
)
if(NOT PELICAN_SHADER_TARGET_ENV_MATCH)
  message(FATAL_ERROR
    "Invalid PELICAN_SHADER_TARGET_ENV: ${PELICAN_SHADER_TARGET_ENV}")
endif()
set(PELICAN_SHADER_TARGET_VULKAN_MAJOR "${CMAKE_MATCH_1}")
set(PELICAN_SHADER_TARGET_VULKAN_MINOR "${CMAKE_MATCH_2}")
set(PELICAN_SHADER_TARGET_VULKAN_VERSION
  "${PELICAN_SHADER_TARGET_VULKAN_MAJOR}.${PELICAN_SHADER_TARGET_VULKAN_MINOR}")

if("${PELICAN_SHADER_TARGET_VULKAN_VERSION}" VERSION_GREATER
   "${PELICAN_VULKAN_API_TARGET_VERSION}")
  message(FATAL_ERROR
    "Shader target ${PELICAN_SHADER_TARGET_ENV} exceeds Vulkan API target "
    "${PELICAN_VULKAN_API_TARGET_VERSION}")
endif()

if(PELICAN_SHADER_TARGET_ENV STREQUAL "vulkan1.0")
  set(PELICAN_SPIRV_TARGET_VERSION "1.0")
elseif(PELICAN_SHADER_TARGET_ENV STREQUAL "vulkan1.1")
  set(PELICAN_SPIRV_TARGET_VERSION "1.3")
elseif(PELICAN_SHADER_TARGET_ENV STREQUAL "vulkan1.2")
  set(PELICAN_SPIRV_TARGET_VERSION "1.5")
elseif(PELICAN_SHADER_TARGET_ENV STREQUAL "vulkan1.3")
  set(PELICAN_SPIRV_TARGET_VERSION "1.6")
else()
  message(FATAL_ERROR
    "Unsupported PELICAN_SHADER_TARGET_ENV: ${PELICAN_SHADER_TARGET_ENV}")
endif()

string(REPLACE "." ";" PELICAN_SPIRV_TARGET_COMPONENTS
  "${PELICAN_SPIRV_TARGET_VERSION}")
list(GET PELICAN_SPIRV_TARGET_COMPONENTS 0 PELICAN_SPIRV_TARGET_MAJOR)
list(GET PELICAN_SPIRV_TARGET_COMPONENTS 1 PELICAN_SPIRV_TARGET_MINOR)
string(REPLACE "." "_" PELICAN_SPIRV_TARGET_VERSION_TOKEN
  "${PELICAN_SPIRV_TARGET_VERSION}")

math(EXPR PELICAN_VULKAN_API_TARGET_VERSION_WORD
  "(${PELICAN_VULKAN_API_TARGET_MAJOR} << 22) | (${PELICAN_VULKAN_API_TARGET_MINOR} << 12) | ${PELICAN_VULKAN_API_TARGET_PATCH}")
math(EXPR PELICAN_SPIRV_TARGET_VERSION_WORD
  "(${PELICAN_SPIRV_TARGET_MAJOR} << 16) | (${PELICAN_SPIRV_TARGET_MINOR} << 8)")

set(PELICAN_SHADER_TARGET_CACHE_ENV
  "vulkan-${PELICAN_SHADER_TARGET_VULKAN_VERSION}")
set(PELICAN_SHADERC_TARGET_ENV_VERSION
  "shaderc_env_version_vulkan_${PELICAN_SHADER_TARGET_VULKAN_MAJOR}_${PELICAN_SHADER_TARGET_VULKAN_MINOR}")
set(PELICAN_SPIRV_TOOLS_TARGET_ENV
  "SPV_ENV_VULKAN_${PELICAN_SHADER_TARGET_VULKAN_MAJOR}_${PELICAN_SHADER_TARGET_VULKAN_MINOR}")
set(PELICAN_SLANG_SPIRV_PROFILE
  "spirv_${PELICAN_SPIRV_TARGET_VERSION_TOKEN}")

add_library(pelican_target_environment INTERFACE)
target_compile_definitions(pelican_target_environment INTERFACE
  PELICAN_VULKAN_API_TARGET_VERSION=${PELICAN_VULKAN_API_TARGET_VERSION_WORD}u
  PELICAN_SHADER_TARGET_ENV_NAME="${PELICAN_SHADER_TARGET_ENV}"
  PELICAN_SHADER_TARGET_CACHE_ENV_NAME="${PELICAN_SHADER_TARGET_CACHE_ENV}"
  PELICAN_SHADERC_TARGET_ENV_VERSION=${PELICAN_SHADERC_TARGET_ENV_VERSION}
  PELICAN_SPIRV_TOOLS_TARGET_ENV=${PELICAN_SPIRV_TOOLS_TARGET_ENV}
  PELICAN_SPIRV_TARGET_VERSION_WORD=${PELICAN_SPIRV_TARGET_VERSION_WORD}u
)

message(STATUS
  "Pelican target contract: Vulkan ${PELICAN_VULKAN_API_TARGET_VERSION}; "
  "${PELICAN_SHADER_TARGET_ENV} / SPIR-V ${PELICAN_SPIRV_TARGET_VERSION}")
